services:
  backend:
    image: delivery-tracker-api
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src

  frontend:
    image: delivery-tracker-web
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_URL
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      


