### Create a new order with MongoDB Schema
POST http://localhost:3000/orders
Content-Type: application/json

{
    "trackerNumber": "ORD-98765ZYX",
    "costumerInfo": {
        "name": "Jane Smith",
        "phone": "987-654-3210",
        "address": "456 Elm St, Townsville, Nation",
        "email": "janesmith@example.com"
    },
    "orderDetails": {
        "items": [
            {
                "itemName": "Grapes",
                "quantity": 5,
                "pricePerItem": 0.6
            },
            {
                "itemName": "Mango",
                "quantity": 4,
                "pricePerItem": 1.0
            },
            {
                "itemName": "Strawberry",
                "quantity": 15,
                "pricePerItem": 0.4
            }
        ],
        "totalPrice": 10.5
    },
    "status": "preparing",
    "statusUpdates": [
        {
            "timestamp": "2023-10-23T11:10:00Z",
            "update": "Order has been confirmed and is currently being prepared."
        }
    ]
}


### PUT an update to an order
PUT http://localhost:3000/orders/ORD-98765ZYX
Content-Type: application/json

{
    "status": "preparing",
    "statusUpdates": [
        {
            "timestamp": "2023-10-23T11:10:00Z",
            "update": "Order has been confirmed and is currently being prepared."
        },
        {
            "timestamp": "2023-10-23T11:15:00Z",
            "update": "Order is being prepared."
        }
    ]
}

### PATCH an update the status of an order
PATCH http://localhost:3000/orders/ORD-98765ZYX/status
Content-Type: application/json

{
    "status": "received"
}